variables:
  COMMON_VERSION: 0.5.0
  PACKAGE_NAME: appserver
  TAG_ENV: Prod
  TAG_PURPOSE: Deploy

before_script:
  - pylint --version
  - echo semgrep $(semgrep --version)

stages:
  - tests
  - build
  - deploy

test:sast:
  retry: 2
  tags:
    - python
  stage: tests
  script:
    - make sast
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: sast-results
    paths:
      - semgrep-ci.json

test:xss:
  retry: 2
  tags:
    - python
  stage: tests
  script:
    - make xss
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: sast-results
    paths:
      - semgrep-flask-xss.json

test:lint:
  retry: 2
  tags:
    - python
  stage: tests
  script:
    - make lint
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: lint-results
    paths:
      - pylint.json

build:docker:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make docker-login
    - make build
  only:
    refs:
      - merge_request
      - main

push:docker:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make docker-login
    - make push
  only:
    refs:
      - main
