version: '3.6'
x-defaults: &defaults
  env_file: .env
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  appserver:
    <<: *defaults
    image: "registry.gitlab.com/trivialsec/appserver/${BUILD_ENV}:${IMAGE_TAG:-latest}"
    container_name: app
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-config.yaml}
      - APP_ENV=${APP_ENV:-Dev}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${TF_VAR_aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${TF_VAR_aws_secret_access_key}
      - AWS_REGION=${AWS_REGION}
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./src/actions:/srv/app/actions
      - ./src/app:/srv/app/app
      - ./src/routes:/srv/app/routes
      - ./src/static:/srv/app/static
      - ./src/templates:/srv/app/templates
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    healthcheck:
      test: curl -f http://localhost:5000/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - app
          - appserver

networks:
  default:
    external:
      name: trivialsec
