

remediations = {
    'SSL Session ID support': {
        'issue': 'Session Hijacking can be achieved if the session ID is previously stolen (XSS, Session Sniffing) and enables gain unauthorized access to the web server',
        'recommendation': 'Applying strict Content Security Policy is the best defense for XXS, and consider HSTS at the top-level domain name to prevent Session Sniffing',
        'confidence': 80,
        'severity_product': 45
    },
    'Session Resumption': {
        'issue': 'a TLS session resumption, being uniquely tied to a specific browser, can be used to track users in the same way cookies might. Essentially, when a browser resumes a session, the web site can correlate the connection with the one that originally created the session, even if the user visits from a different network. University of Hamburg research paper concluded, the average user can be tracked for up to eight day',
        'recommendation': 'Allow session resumption for first-party domains but not third-parties, to prevent unauthorised user tracking',
        'confidence': 100,
        'severity_product': 90
    },
    'Anonymous NULL Ciphers': {
        'issue': 'A null cipher, or concealment cipher, which are highly vulnerable to man in the middle attacks',
        'recommendation': 'Disable anonymous and weak cipher suites by manually explicitly configuring ciphers on the web server',
        'confidence': 90,
        'severity_product': 95
    },
    'Trust (hostname)': {
        'issue': 'The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address',
        'recommendation': 'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',
        'confidence': 70,
        'severity_product': 75
    },
    'EV cert (experimental)': {
        'issue': 'Extended Validation (EV) certificates provide protections against domain take-over attacks that utilise the IP churn inherent nature of many cloud service providors to take advantage of the automated issuance of Domain Validated (DV) certificates',
        'recommendation': 'If you are using Domain Validated (DV) certificates you should at least upgrade to EV or prefereably an Organization validated (OV) certificate that can not be as easily used in attacks that rely on automated certificate issuance',
        'confidence': 100,
        'severity_product': 85
    },
    'In pwnedkeys.com DB': {
        'issue': 'pwnedkeys.com makes available to anyone a large collection of private keys that can be used to decrypt assumed secure communications using SSL/TLS',
        'recommendation': 'Immediately replace the exposed key and investigate the cause and vector of the compromise to ensure the new private key is not also compromised',
        'confidence': 100,
        'severity_product': 95
    },
    'OCSP stapling': {
        'issue': 'OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.',
        'recommendation': 'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',
        'confidence': 100,
        'severity_product': 65
    },
    'OCSP must staple extension': {
        'issue': 'OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.',
        'recommendation': 'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',
        'confidence': 100,
        'severity_product': 65
    },
    'Public Key Pinning': {
        'issue': 'The original problem was the Key Distribution Problem. Insecure communications can be transformed into a secure communication problem with encryption. Encrypted communications can be transformed into an identity problem with signatures. The identity problem terminates at the key distribution problem. They are the same problem. Pinning leverages knowledge of the pre-existing relationship between the user and an organization or service to help make better security related decisions. Because you already have information on the server or service, you don’t need to rely on generalized mechanisms meant to solve the key distribution problem. That is, you don’t need to turn to DNS for name/address mappings or CAs for bindings and status.',
        'recommendation': 'There are three steps needed to address the issue of key distribution, first is to know and access to the peer, server or service. Next chose a trust model (web of trust, or hierarchy of trust) which essentially will confer trust. Last associate "pin" a host with their expected X509 certificate or public key by adding this certificate or public key to the requesting application at development time. Do not attempt to preloading it out of band in hostile internet connected environments, which negates the intent entirely. Consider OCSP must-staple flag on the certificate to address the limitation of pinning that is revocation, because Pinning is not Stapling. Stapling sends both the certificate and OCSP responder information in the same request to avoid the additional fetches the client should perform during path validations',
        'confidence': 100,
        'severity_product': 65
    },
    'OCSP URI': {
        'issue': 'OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.',
        'recommendation': 'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',
        'confidence': 70,
        'severity_product': 75
    },
    'X-XSS-Protection': {
        'issue': 'This header enables the Cross-site scripting (XSS) filter in your browser, without it the browser will by default do nothing to protect from XSS',
        'recommendation': 'With the filter enabled in blocking mode, rather than sanitize the page, when a XSS attack is detected, the browser will prevent rendering of the page',
        'confidence': 100,
        'severity_product': 95
    },
    'X-Content-Type-Options': {
        'issue': 'Setting this header will prevent the browser from interpreting files as something else than declared by the content type in the HTTP headers',
        'recommendation': 'Use the "nosnif" setting which Will prevent the browser from MIME-sniffing a response away from the declared content-type',
        'confidence': 100,
        'severity_product': 95
    },
}


sql = "INSERT INTO `finding_details` (`title`,`description`,`type_namespace`,`type_category`,`type_classifier`,`severity_product`,`recommendation`,`recommendation_url`) VALUES ("
statments = [
    "'Public Key Pinning not offered','The original problem was the Key Distribution Problem. Insecure communications can be transformed into a secure communication problem with encryption. Encrypted communications can be transformed into an identity problem with signatures. The identity problem terminates at the key distribution problem. They are the same problem. Pinning leverages knowledge of the pre-existing relationship between the user and an organization or service to help make better security related decisions. Because you already have information on the server or service, you don’t need to rely on generalized mechanisms meant to solve the key distribution problem. That is, you don’t need to turn to DNS for name/address mappings or CAs for bindings and status.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'There are three steps needed to address the issue of key distribution, first is to know and access to the peer, server or service. Next chose a trust model (web of trust, or hierarchy of trust) which essentially will confer trust. Last associate \"pin\" a host with their expected X509 certificate or public key by adding this certificate or public key to the requesting application at development time. Do not attempt to preloading it out of band in hostile internet connected environments, which negates the intent entirely. Consider OCSP must-staple flag on the certificate to address the limitation of pinning that is revocation, because Pinning is not Stapling. Stapling sends both the certificate and OCSP responder information in the same request to avoid the additional fetches the client should perform during path validations',NULL",
    "'Security headers not offered','HTTP header fields are part of HTTP message defined in RFC 2616 that consists of requests from client to server and responses from server to client that define parameters for the communication process including: language, compression support, security and a lot of resources.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'We recommend planning an incremental inclusion of Headers like:\nPublic Key Pinning Extension for HTTP (HPKP)\nHTTP Strict Transport Security (HSTS)\nContent Security Policy (CSP)',NULL",
    "'OCSP must staple extension not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'Session Ticket RFC 5077 hint no lifetime advertised','A single compromised machine enables an attacker to decrypt traffic passively across the whole internet of devices by simply exfiltrating a short key every rotation period. Session Ticket Encryption Key can passively decrypt all connections that support Session Tickets, resumed and not. Using different STEKs across geographical locations or STEKs rotated or destroyed periodically to avoid compromise is effectively unfeasible and not implemented in any webserver but theoretically disables session resumption and any STEK benefits, but will offer offer Forward Secrecy once more','Software and Configuration Checks','Vulnerabilities','SSL/TLS',50,'TLS 1.3 solves this by not sending session keys (tickets) in plaintext to the server',NULL",
    "'SSL Session ID support risk of third-party user tracking','Session Hijacking can be achieved if the session ID is previously stolen (XSS, Session Sniffing) and enables gain unauthorized access to the web server','Software and Configuration Checks','Vulnerabilities','SSL/TLS',45,'Applying strict Content Security Policy is the best defense for XXS, and consider HSTS at the top-level domain name to prevent Session Sniffing',NULL",
    "'EV cert (experimental) no','Extended Validation (EV) certificates provide protections against domain take-over attacks that utilise the IP churn inherent nature of many cloud service providors to take advantage of the automated issuance of Domain Validated (DV) certificates','Software and Configuration Checks','Vulnerabilities','SSL/TLS',85,'If you are using Domain Validated (DV) certificates you should at least upgrade to EV or prefereably an Organization validated (OV) certificate that can not be as easily used in attacks that rely on automated certificate issuance',NULL",
    "'X-Frame-Options potential clickjacking risk','X-Frame-Options response header improve the protection of web applications against Clickjacking. It declares a policy communicated from a host to the client browser on whether the browser must not display the transmitted content in frames of other web pages','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'Valid values are:\n\"deny\": No rendering within a frame\n\"sameorigin\": No rendering if origin mismatch\n\"allow-from: DOMAIN\": Allows rendering if framed by frame loaded from DOMAIN',NULL",
    "'X-XSS-Protection site allows XSS','This header enables the Cross-site scripting (XSS) filter in your browser, without it the browser will by default do nothing to protect from XSS','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'With the filter enabled in blocking mode, rather than sanitize the page, when a XSS attack is detected, the browser will prevent rendering of the page',NULL",
    "'X-Content-Type-Options malicious code delivery','Setting this header will prevent the browser from interpreting files as something else than declared by the content type in the HTTP headers','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'Use the \"nosnif\" setting which Will prevent the browser from MIME-sniffing a response away from the declared content-type',NULL",
    "'Referrer-Policy sensitive information leakage risk','Some communication methods send or store values, sometimes sensitive, in the url and can be shared with arbitrary third parties through this header','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'using \"no-referrer\" will omit the header entirely. No referrer information is sent along with requests. Alternetively use \"strict-origin\" which only sends the origin of the document as the referrer to a-priori as-much-secure destination (HTTPS->HTTPS), but will not send it to a less secure destination (HTTPS->HTTP).',NULL",
    "'Trust (hostname) Ok via SAN (SNI mandatory)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'CWE-310','cipherlist_AVERAGE offered ','Software and Configuration Checks','Vulnerabilities','CWE',30,NULL,NULL",
    "'insecure_redirect','Redirect to insecure URL: \'https://gitlab.com/users/sign_in\' ','Software and Configuration Checks','Vulnerabilities','insecure_redirect',80,NULL,NULL",
    "'HSTS_multiple','Multiple HSTS headers. Using first header: max-age=31536000 ','Software and Configuration Checks','Vulnerabilities','HSTS_multiple',60,NULL,NULL",
    "'X-Frame-Options_multiple','Multiple X-Frame-Options headers. Using first header: DENY ','Software and Configuration Checks','Vulnerabilities','X-Frame-Options_multiple',60,NULL,NULL",
    "'X-XSS-Protection_multiple','Multiple X-XSS-Protection headers. Using first header: 1; mode=block ','Software and Configuration Checks','Vulnerabilities','X-XSS-Protection_multiple',60,NULL,NULL",
    "'X-Content-Type-Options_multiple','Multiple X-Content-Type-Options headers. Using first header: nosniff ','Software and Configuration Checks','Vulnerabilities','X-Content-Type-Options_multiple',60,NULL,NULL",
    "'Referrer-Policy_multiple','Multiple Referrer-Policy headers. Using first header :strict-origin-when-cross-origin ','Software and Configuration Checks','Vulnerabilities','Referrer-Policy_multiple',60,NULL,NULL",
    "' uses TLS CBC ciphers','LUCKY13 potentially vulnerable CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'Content-Security-Policy Risk of XSS','CSP prevents a wide range of attacks, including Cross-site scripting and other cross-site injections, but has significant impact on the way browsers render pages (e.g., inline JavaScript disabled by default and must be explicitly allowed in policy)','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'A Content Security Policy (CSP) requires careful tuning and precise definition of the policy. If enabled, various directives are important security features and almost never represent intended functions, \"block-all-mixed-content\" and \"reflected-xss\" are the most obvious in this category',NULL",
    "'Trust (hostname) Ok via SAN (same w/o SNI)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'insecure_redirect','Redirect to insecure URL: \'http://next.langton.cloud/index.php/login\' ','Software and Configuration Checks','Vulnerabilities','insecure_redirect',80,NULL,NULL",
    "'X-Frame-Options_multiple','Multiple X-Frame-Options headers. Using first header: SAMEORIGIN ','Software and Configuration Checks','Vulnerabilities','X-Frame-Options_multiple',60,NULL,NULL",
    "' uses gzip HTTP compression  - only supplied \'/\' tested','BREACH potentially VULNERABLE CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',80,NULL,NULL",
    "'Public Key Pinning not offered','The original problem was the Key Distribution Problem. Insecure communications can be transformed into a secure communication problem with encryption. Encrypted communications can be transformed into an identity problem with signatures. The identity problem terminates at the key distribution problem. They are the same problem. Pinning leverages knowledge of the pre-existing relationship between the user and an organization or service to help make better security related decisions. Because you already have information on the server or service, you don’t need to rely on generalized mechanisms meant to solve the key distribution problem. That is, you don’t need to turn to DNS for name/address mappings or CAs for bindings and status.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'There are three steps needed to address the issue of key distribution, first is to know and access to the peer, server or service. Next chose a trust model (web of trust, or hierarchy of trust) which essentially will confer trust. Last associate \"pin\" a host with their expected X509 certificate or public key by adding this certificate or public key to the requesting application at development time. Do not attempt to preloading it out of band in hostile internet connected environments, which negates the intent entirely. Consider OCSP must-staple flag on the certificate to address the limitation of pinning that is revocation, because Pinning is not Stapling. Stapling sends both the certificate and OCSP responder information in the same request to avoid the additional fetches the client should perform during path validations',NULL",
    "'Security headers not offered','HTTP header fields are part of HTTP message defined in RFC 2616 that consists of requests from client to server and responses from server to client that define parameters for the communication process including: language, compression support, security and a lot of resources.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'We recommend planning an incremental inclusion of Headers like:\nPublic Key Pinning Extension for HTTP (HPKP)\nHTTP Strict Transport Security (HSTS)\nContent Security Policy (CSP)',NULL",
    "'OCSP must staple extension not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'Strict Transport Security not offered','HSTS is a web security policy mechanism that helps to protect websites against protocol downgrade attacks but often is not implemented in a misplaced fear of service outage when HTTPS can no longer be served on the domain. The initial request, or requests made after the max age setting, remains unprotected from active attacks if it uses an insecure protocol.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'HSTS hosts should declare HSTS policy at the top-level domain name. Consider also applying strict Content Security Policy',NULL",
    "'Session Ticket RFC 5077 hint no lifetime advertised','A single compromised machine enables an attacker to decrypt traffic passively across the whole internet of devices by simply exfiltrating a short key every rotation period. Session Ticket Encryption Key can passively decrypt all connections that support Session Tickets, resumed and not. Using different STEKs across geographical locations or STEKs rotated or destroyed periodically to avoid compromise is effectively unfeasible and not implemented in any webserver but theoretically disables session resumption and any STEK benefits, but will offer offer Forward Secrecy once more','Software and Configuration Checks','Vulnerabilities','SSL/TLS',50,'TLS 1.3 solves this by not sending session keys (tickets) in plaintext to the server',NULL",
    "'SSL Session ID support risk of third-party user tracking','Session Hijacking can be achieved if the session ID is previously stolen (XSS, Session Sniffing) and enables gain unauthorized access to the web server','Software and Configuration Checks','Vulnerabilities','SSL/TLS',45,'Applying strict Content Security Policy is the best defense for XXS, and consider HSTS at the top-level domain name to prevent Session Sniffing',NULL",
    "'Trust (hostname) certificate does not match supplied URI','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'EV cert (experimental) no','Extended Validation (EV) certificates provide protections against domain take-over attacks that utilise the IP churn inherent nature of many cloud service providors to take advantage of the automated issuance of Domain Validated (DV) certificates','Software and Configuration Checks','Vulnerabilities','SSL/TLS',85,'If you are using Domain Validated (DV) certificates you should at least upgrade to EV or prefereably an Organization validated (OV) certificate that can not be as easily used in attacks that rely on automated certificate issuance',NULL",
    "'Trust (hostname) certificate does not match supplied URI (same w/o SNI)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'CWE-310','cipherlist_AVERAGE offered ','Software and Configuration Checks','Vulnerabilities','CWE',30,NULL,NULL",
    "'cert_trust','certificate does not match supplied URI (same w/o SNI) ','Software and Configuration Checks','Vulnerabilities','cert_trust',80,NULL,NULL",
    "'HSTS','not offered ','Software and Configuration Checks','Vulnerabilities','HSTS',30,NULL,NULL",
    "'security_headers','-- ','Software and Configuration Checks','Vulnerabilities','security_headers',60,NULL,NULL",
    "' uses TLS CBC ciphers','LUCKY13 potentially vulnerable CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'X-Frame-Options potential clickjacking risk','X-Frame-Options response header improve the protection of web applications against Clickjacking. It declares a policy communicated from a host to the client browser on whether the browser must not display the transmitted content in frames of other web pages','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'Valid values are:\n\"deny\": No rendering within a frame\n\"sameorigin\": No rendering if origin mismatch\n\"allow-from: DOMAIN\": Allows rendering if framed by frame loaded from DOMAIN',NULL",
    "'Trust (hostname) Ok via SAN (same w/o SNI)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "' uses gzip HTTP compression  - only supplied \'/\' tested','BREACH potentially VULNERABLE CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',80,NULL,NULL",
    "'No ciphers supporting Forward Secrecy offered','PFS prevents an attacker from being able to access data from a group of transactions even if a single communication is compromised all others are safe and requrie the exact same effort to compromise as the first','Software and Configuration Checks','Vulnerabilities','SSL/TLS',85,'Configure your web servers to utilise the suitable cipher suites. Currently, key exchanges that are compliant are: Ephemeral Diffie-Hellman (DHE) and Ephemeral Elliptic Curve Diffie-Hellman (ECDHE)',NULL",
    "'Session Ticket RFC 5077 hint no lifetime advertised','A single compromised machine enables an attacker to decrypt traffic passively across the whole internet of devices by simply exfiltrating a short key every rotation period. Session Ticket Encryption Key can passively decrypt all connections that support Session Tickets, resumed and not. Using different STEKs across geographical locations or STEKs rotated or destroyed periodically to avoid compromise is effectively unfeasible and not implemented in any webserver but theoretically disables session resumption and any STEK benefits, but will offer offer Forward Secrecy once more','Software and Configuration Checks','Vulnerabilities','SSL/TLS',50,'TLS 1.3 solves this by not sending session keys (tickets) in plaintext to the server',NULL",
    "'SSL Session ID support risk of third-party user tracking','Session Hijacking can be achieved if the session ID is previously stolen (XSS, Session Sniffing) and enables gain unauthorized access to the web server','Software and Configuration Checks','Vulnerabilities','SSL/TLS',45,'Applying strict Content Security Policy is the best defense for XXS, and consider HSTS at the top-level domain name to prevent Session Sniffing',NULL",
    "'TLS1_2','not offered ','Software and Configuration Checks','Vulnerabilities','TLS1_2',60,NULL,NULL",
    "'TLS1_3','not offered ','Software and Configuration Checks','Vulnerabilities','TLS1_3',30,NULL,NULL",
    "'cipherlist_STRONG','not offered ','Software and Configuration Checks','Vulnerabilities','cipherlist_STRONG',60,NULL,NULL",
    "'PFS','No ciphers supporting (P)FS offered ','Software and Configuration Checks','Vulnerabilities','PFS',60,NULL,NULL",
    "'cipher_order','NOT a cipher order configured ','Software and Configuration Checks','Vulnerabilities','cipher_order',80,NULL,NULL",
    "'protocol_negotiated','Default protocol empty ','Software and Configuration Checks','Vulnerabilities','protocol_negotiated',0,NULL,NULL",
    "'cipher_negotiated','Default cipher empty  (limited sense as client will pick) ','Software and Configuration Checks','Vulnerabilities','cipher_negotiated',0,NULL,NULL",
    "'sessionresumption_ID','check failed because of connect problem ','Software and Configuration Checks','Vulnerabilities','sessionresumption_ID',0,NULL,NULL",
    "'CWE-310','secure_renego OpenSSL handshake didn\'t succeed ','Software and Configuration Checks','Vulnerabilities','CWE',0,NULL,NULL",
    "'fallback_SCSV','Check failed. (couldn\'t connect) ','Software and Configuration Checks','Vulnerabilities','fallback_SCSV',0,NULL,NULL",
    "'Public Key Pinning not offered','The original problem was the Key Distribution Problem. Insecure communications can be transformed into a secure communication problem with encryption. Encrypted communications can be transformed into an identity problem with signatures. The identity problem terminates at the key distribution problem. They are the same problem. Pinning leverages knowledge of the pre-existing relationship between the user and an organization or service to help make better security related decisions. Because you already have information on the server or service, you don’t need to rely on generalized mechanisms meant to solve the key distribution problem. That is, you don’t need to turn to DNS for name/address mappings or CAs for bindings and status.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'There are three steps needed to address the issue of key distribution, first is to know and access to the peer, server or service. Next chose a trust model (web of trust, or hierarchy of trust) which essentially will confer trust. Last associate \"pin\" a host with their expected X509 certificate or public key by adding this certificate or public key to the requesting application at development time. Do not attempt to preloading it out of band in hostile internet connected environments, which negates the intent entirely. Consider OCSP must-staple flag on the certificate to address the limitation of pinning that is revocation, because Pinning is not Stapling. Stapling sends both the certificate and OCSP responder information in the same request to avoid the additional fetches the client should perform during path validations',NULL",
    "'OCSP must staple extension not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'insecure downgrade of protocol TLSv1.0 for IE 8 Win 7','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'insecure downgrade of protocol TLSv1.0 for Java 7u25','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'TLS 1.3 downgraded to a weaker protocol','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'Session Ticket RFC 5077 hint no lifetime advertised','A single compromised machine enables an attacker to decrypt traffic passively across the whole internet of devices by simply exfiltrating a short key every rotation period. Session Ticket Encryption Key can passively decrypt all connections that support Session Tickets, resumed and not. Using different STEKs across geographical locations or STEKs rotated or destroyed periodically to avoid compromise is effectively unfeasible and not implemented in any webserver but theoretically disables session resumption and any STEK benefits, but will offer offer Forward Secrecy once more','Software and Configuration Checks','Vulnerabilities','SSL/TLS',50,'TLS 1.3 solves this by not sending session keys (tickets) in plaintext to the server',NULL",
    "'SSL Session ID support risk of third-party user tracking','Session Hijacking can be achieved if the session ID is previously stolen (XSS, Session Sniffing) and enables gain unauthorized access to the web server','Software and Configuration Checks','Vulnerabilities','SSL/TLS',45,'Applying strict Content Security Policy is the best defense for XXS, and consider HSTS at the top-level domain name to prevent Session Sniffing',NULL",
    "'OCSP stapling not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'X-Frame-Options potential clickjacking risk','X-Frame-Options response header improve the protection of web applications against Clickjacking. It declares a policy communicated from a host to the client browser on whether the browser must not display the transmitted content in frames of other web pages','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'Valid values are:\n\"deny\": No rendering within a frame\n\"sameorigin\": No rendering if origin mismatch\n\"allow-from: DOMAIN\": Allows rendering if framed by frame loaded from DOMAIN',NULL",
    "'Content-Security-Policy Risk of XSS','CSP prevents a wide range of attacks, including Cross-site scripting and other cross-site injections, but has significant impact on the way browsers render pages (e.g., inline JavaScript disabled by default and must be explicitly allowed in policy)','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'A Content Security Policy (CSP) requires careful tuning and precise definition of the policy. If enabled, various directives are important security features and almost never represent intended functions, \"block-all-mixed-content\" and \"reflected-xss\" are the most obvious in this category',NULL",
    "'Trust (hostname) Ok via SAN (same w/o SNI)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'CWE-310','cipherlist_AVERAGE offered ','Software and Configuration Checks','Vulnerabilities','CWE',30,NULL,NULL",
    "'OCSP_stapling','not offered ','Software and Configuration Checks','Vulnerabilities','OCSP_stapling',30,NULL,NULL",
    "'SSL ID Flipping, high CPU usage','secure_client_renego VULNERABLE CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',80,NULL,NULL",
    "'fallback_SCSV','received non-RFC-compliant \'handshake failure\' instead of \'inappropriate fallback\' ','Software and Configuration Checks','Vulnerabilities','fallback_SCSV',60,NULL,NULL",
    "'CVE-2011-3389','BEAST VULNERABLE -- but also supports higher protocols  TLSv1.1 TLSv1.2 (likely mitigated) ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "' uses TLS CBC ciphers','LUCKY13 potentially vulnerable CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'Security headers not offered','HTTP header fields are part of HTTP message defined in RFC 2616 that consists of requests from client to server and responses from server to client that define parameters for the communication process including: language, compression support, security and a lot of resources.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'We recommend planning an incremental inclusion of Headers like:\nPublic Key Pinning Extension for HTTP (HPKP)\nHTTP Strict Transport Security (HSTS)\nContent Security Policy (CSP)',NULL",
    "'Strict Transport Security not offered','HSTS is a web security policy mechanism that helps to protect websites against protocol downgrade attacks but often is not implemented in a misplaced fear of service outage when HTTPS can no longer be served on the domain. The initial request, or requests made after the max age setting, remains unprotected from active attacks if it uses an insecure protocol.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'HSTS hosts should declare HSTS policy at the top-level domain name. Consider also applying strict Content Security Policy',NULL",
    "'Session Resumption risk of third-party user tracking','a TLS session resumption, being uniquely tied to a specific browser, can be used to track users in the same way cookies might. Essentially, when a browser resumes a session, the web site can correlate the connection with the one that originally created the session, even if the user visits from a different network. University of Hamburg research paper concluded, the average user can be tracked for up to eight day','Software and Configuration Checks','Vulnerabilities','SSL/TLS',90,'Allow session resumption for first-party domains but not third-parties, to prevent unauthorised user tracking',NULL",
    "'EV cert (experimental) no','Extended Validation (EV) certificates provide protections against domain take-over attacks that utilise the IP churn inherent nature of many cloud service providors to take advantage of the automated issuance of Domain Validated (DV) certificates','Software and Configuration Checks','Vulnerabilities','SSL/TLS',85,'If you are using Domain Validated (DV) certificates you should at least upgrade to EV or prefereably an Organization validated (OV) certificate that can not be as easily used in attacks that rely on automated certificate issuance',NULL",
    "'HSTS','not offered ','Software and Configuration Checks','Vulnerabilities','HSTS',30,NULL,NULL",
    "'Trust (hostname) Ok via SAN (SNI mandatory)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'Public Key Pinning not offered','The original problem was the Key Distribution Problem. Insecure communications can be transformed into a secure communication problem with encryption. Encrypted communications can be transformed into an identity problem with signatures. The identity problem terminates at the key distribution problem. They are the same problem. Pinning leverages knowledge of the pre-existing relationship between the user and an organization or service to help make better security related decisions. Because you already have information on the server or service, you don’t need to rely on generalized mechanisms meant to solve the key distribution problem. That is, you don’t need to turn to DNS for name/address mappings or CAs for bindings and status.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'There are three steps needed to address the issue of key distribution, first is to know and access to the peer, server or service. Next chose a trust model (web of trust, or hierarchy of trust) which essentially will confer trust. Last associate \"pin\" a host with their expected X509 certificate or public key by adding this certificate or public key to the requesting application at development time. Do not attempt to preloading it out of band in hostile internet connected environments, which negates the intent entirely. Consider OCSP must-staple flag on the certificate to address the limitation of pinning that is revocation, because Pinning is not Stapling. Stapling sends both the certificate and OCSP responder information in the same request to avoid the additional fetches the client should perform during path validations',NULL",
    "'Security headers not offered','HTTP header fields are part of HTTP message defined in RFC 2616 that consists of requests from client to server and responses from server to client that define parameters for the communication process including: language, compression support, security and a lot of resources.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'We recommend planning an incremental inclusion of Headers like:\nPublic Key Pinning Extension for HTTP (HPKP)\nHTTP Strict Transport Security (HSTS)\nContent Security Policy (CSP)',NULL",
    "'OCSP must staple extension not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'insecure downgrade of protocol TLSv1.0 for IE 8 Win 7','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'insecure downgrade of protocol TLSv1.0 for Java 7u25','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'TLS 1.3 downgraded to a weaker protocol','In most cases the connection requires the highest protocol version supported by the client, or to be no greater than the highest protocol version supported by the server, which may result in a hostile negotiation to the lowest supported version offered by the server to enable an attack that compromises the client','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'Either enforce HSTS or fail the connection with an error message that is displayed to the user',NULL",
    "'Strict Transport Security not offered','HSTS is a web security policy mechanism that helps to protect websites against protocol downgrade attacks but often is not implemented in a misplaced fear of service outage when HTTPS can no longer be served on the domain. The initial request, or requests made after the max age setting, remains unprotected from active attacks if it uses an insecure protocol.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'HSTS hosts should declare HSTS policy at the top-level domain name. Consider also applying strict Content Security Policy',NULL",
    "'Triple DES Ciphers insecure cipher negotiation','Data Encryption Standard (DES), the algorithm 3DES is based on, was retired in 2005. The two-key variant of 3DES was retired in 2015.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'The Sweet32 attack on 3DES can be mitigated by rekeying the session frequently, not standard for many webservers, the most effective solution is to stop offering legacy 64-bit block ciphers',NULL",
    "'EV cert (experimental) no','Extended Validation (EV) certificates provide protections against domain take-over attacks that utilise the IP churn inherent nature of many cloud service providors to take advantage of the automated issuance of Domain Validated (DV) certificates','Software and Configuration Checks','Vulnerabilities','SSL/TLS',85,'If you are using Domain Validated (DV) certificates you should at least upgrade to EV or prefereably an Organization validated (OV) certificate that can not be as easily used in attacks that rely on automated certificate issuance',NULL",
    "'OCSP stapling not offered','OCSP stapling simultaneously decrease page load times and increase user security, without stapling OCSP alone will result in an excessive amount of checks being made to the CA, also  the client had no idea that the site in question supports OCSP and whether or not it should expect them to staple an OCSP response.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',65,'To address the certificate revocation, performance issues, and the uncertainty in OCSP support, set the OCSP must-staple flag (by your CA in the certificate they generate for you) when you obtain your replacement certificates. Finally, ensure the server openssl is configured with the appropriate extension to support OCSP must-staple',NULL",
    "'Trust (hostname) Ok via SAN (same w/o SNI)','The certificate does not match supplied URI which would allow Man in the Middle attacks on the client. Hostname verification is a client-side responcibility that many common client implementations fail to address','Software and Configuration Checks','Vulnerabilities','SSL/TLS',75,'To provide a higher degree of safety to clients that use hostname verification, make sure your X.509 certificate has the correct subjectAltName field set correctly',NULL",
    "'CWE-310','cipherlist_3DES_IDEA offered ','Software and Configuration Checks','Vulnerabilities','CWE',60,NULL,NULL",
    "'CWE-310','cipherlist_AVERAGE offered ','Software and Configuration Checks','Vulnerabilities','CWE',30,NULL,NULL",
    "'cipher_negotiated','AES256-SHA256 (cbc) ','Software and Configuration Checks','Vulnerabilities','cipher_negotiated',30,NULL,NULL",
    "'OCSP_stapling','not offered ','Software and Configuration Checks','Vulnerabilities','OCSP_stapling',30,NULL,NULL",
    "'HSTS','not offered ','Software and Configuration Checks','Vulnerabilities','HSTS',30,NULL,NULL",
    "'security_headers','-- ','Software and Configuration Checks','Vulnerabilities','security_headers',60,NULL,NULL",
    "'CVE-2016-2183 CVE-2016-6329','SWEET32 uses 64 bit block ciphers ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'CVE-2011-3389','BEAST VULNERABLE -- but also supports higher protocols  TLSv1.1 TLSv1.2 (likely mitigated) ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "' uses TLS CBC ciphers','LUCKY13 potentially vulnerable CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'HSTS_time','0. HSTS is disabled ','Software and Configuration Checks','Vulnerabilities','HSTS_time',30,NULL,NULL",
    "'OCSP_stapling <cert#1>','not offered ','Software and Configuration Checks','Vulnerabilities','OCSP_stapling <cert#1>',30,NULL,NULL",
    "'OCSP_stapling <cert#2>','not offered ','Software and Configuration Checks','Vulnerabilities','OCSP_stapling <cert#2>',30,NULL,NULL",
    "'Triple DES Ciphers insecure cipher negotiation','Data Encryption Standard (DES), the algorithm 3DES is based on, was retired in 2005. The two-key variant of 3DES was retired in 2015.','Software and Configuration Checks','Vulnerabilities','SSL/TLS',95,'The Sweet32 attack on 3DES can be mitigated by rekeying the session frequently, not standard for many webservers, the most effective solution is to stop offering legacy 64-bit block ciphers',NULL",
    "'CWE-327','cipherlist_LOW offered ','Software and Configuration Checks','Vulnerabilities','CWE',80,NULL,NULL",
    "'CWE-310','cipherlist_3DES_IDEA offered ','Software and Configuration Checks','Vulnerabilities','CWE',60,NULL,NULL",
    "'DH_groups','RFC2409/Oakley Group 2 ','Software and Configuration Checks','Vulnerabilities','DH_groups',60,NULL,NULL",
    "' 256 bit ECDH (P-256) (cbc)','cipher_negotiated ECDHE-RSA-AES256-SHA384 , ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'CVE-2016-2183 CVE-2016-6329','SWEET32 uses 64 bit block ciphers ','Software and Configuration Checks','Vulnerabilities','CVE',30,NULL,NULL",
    "'CVE-2015-4000','LOGJAM-common_primes RFC2409/Oakley Group 2 ','Software and Configuration Checks','Vulnerabilities','CVE',80,NULL,NULL",
    "' Detected ciphers: RC4-SHA RC4-MD5','RC4 VULNERABLE CWE-310, ','Software and Configuration Checks','Vulnerabilities','CVE',80,NULL,NULL",
    "'cipher_negotiated','AES256-SHA (cbc) ','Software and Configuration Checks','Vulnerabilities','cipher_negotiated',30,NULL,NULL",
    "'CWE-310','secure_renego VULNERABLE ','Software and Configuration Checks','Vulnerabilities','CWE',90,NULL,NULL",
    "'TLS_session_ticket','valid for 216000 seconds (>daily) ','Software and Configuration Checks','Vulnerabilities','TLS_session_ticket',30,NULL,NULL",
    "'CWE-310','secure_renego OpenSSL handshake didn\'t succeed ','Software and Configuration Checks','Vulnerabilities','CWE',0,NULL,NULL",
]

for statment in statments:
    title, description, type_namespace, type_category, type_classifier, severity_product, recommendation, recommendation_url, *_ = statment.split(',')
    print(title)
    print(description)
    print(type_namespace)
    print(type_category)
    print(type_classifier)
    print(severity_product)
    print(recommendation)
    print(recommendation_url)
    exit(0)